# Generated by Django 3.2.3 on 2023-09-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество ингридиента'),
        ),
    ]
