# Generated by Django 3.2.3 on 2023-09-14 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0013_remove_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец корзины покупок')),
            ],
            options={
                'verbose_name': 'Корзины покупок',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['id'], 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['id'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['id'], 'verbose_name': 'Соответствия рецепта и ингредиентов'},
        ),
        migrations.AlterModelOptions(
            name='recipetag',
            options={'ordering': ['id'], 'verbose_name': 'Соответствия рецепта и тегов'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.CreateModel(
            name='ShoppingCartRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts_recipes', to='recipes.recipe', verbose_name='Рецепт')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_carts_recipes', to='recipes.shoppingcart', verbose_name='Корзина покупок')),
            ],
            options={
                'verbose_name': 'Соответствия корзины покупок и рецептов',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='recipes',
            field=models.ManyToManyField(through='recipes.ShoppingCartRecipe', to='recipes.Recipe', verbose_name='Рецепты'),
        ),
    ]
