# Generated by Django 3.2.3 on 2023-09-24 11:59

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='cannot_subscribe_yourself',
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('author_id', django.db.models.expressions.F('subscriber_id')), _negated=True), name='cannot_subscribe_yourself'),
        ),
    ]
