# Generated by Django 3.2.3 on 2023-09-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230904_1550'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
