# Generated by Django 3.2.3 on 2023-09-24 12:02

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230924_2101'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='cannot_subscribe_yourself',
        ),
        migrations.RemoveConstraint(
            model_name='subscribe',
            name='unique_subscriber',
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('author', 'subscriber'), name='unique_subscriber'),
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('author', django.db.models.expressions.F('subscriber')), _negated=True), name='cannot_subscribe_yourself'),
        ),
    ]
